
version: 2

sources:
  - name: ga4_obfuscated_sample_ecommerce
    database: bigquery-public-data
    tables:
      - name: events_*
  - name: dbt_test_marvin
    database: formation-sql-316408
    tables:
      - name: sessions

models:
  - name: sessions_category
    columns:
      - name: Date
        tests:
          - not_null
      - name: session_id
      - name: category
      - name: country

models:
  - name: primary_key
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique

models:
  - name: sessions
    columns:
      - name: primary_key
      - name: Date
      - name: country
      - name: category
      - name: sessions