
version: 2

sources:
  - name: ga4_obfuscated_sample_ecommerce
    database: bigquery-public-data
    tables:
      - name: events_*

models:
  - name: sessions_category
    columns:
      - name: Date
        tests:
          - not_null
      - name: session_id
      - name: category
      - name: country

models:
  - name: sessions
    columns:
      - name: primary_key
        tests:
          - unique
          - not_null
      - name: Date
      - name: country
      - name: category
      - name: sessions